[deps]
DiffEqCallbacks = "459566f4-90b8-5000-8ac3-15dfb0a30def"
ForwardDiff = "f6369f11-7733-5829-9624-2563aa707210"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
QuadGK = "1fd47b50-473d-5c70-9696-f719f8f3bcdc"
SimpleNonlinearSolve = "727e6d20-b764-4bd8-a329-72de5adea6c7"
SummationByPartsOperators = "9f78cca6-572e-554e-b819-917d2f1cf240"
Trixi = "a7f1ee26-1774-49b1-8366-f1abc58fbfcb"

[preferences.OrdinaryDiffEq]
PrecompileAutoSpecialize = false
PrecompileAutoSwitch = false
PrecompileDefaultSpecialize = false
PrecompileFunctionWrapperSpecialize = false
PrecompileLowStorage = false
PrecompileNoSpecialize = false
PrecompileNonStiff = false
PrecompileStiff = false
